public class MyStandardClass {

    String property='Hi';
    
    //property = property+' Hero';
    
    public void method1() {
    try {
        System.debug('---->'+property);
        throw new ConnectionException ('The assigned value is incorrect');
     }catch(NullpointerException slfjsdlfds) {
     
     }catch (ConnectionException ce) {
     
     }catch( Exception e) {
     
     }
     
    }
    
}